# Generated by Django 2.1.1 on 2018-09-20 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appa', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='Job',
        ),
        migrations.RenameModel(
            old_name='Notifications',
            new_name='Notification',
        ),
        migrations.RenameModel(
            old_name='Posts',
            new_name='Post',
        ),
    ]
