# Generated by Django 2.1.1 on 2018-09-20 23:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appa', '0003_auto_20180920_2329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.RemoveField(
            model_name='skill',
            name='user',
        ),
        migrations.AddField(
            model_name='registrationform',
            name='Experience',
            field=models.CharField(default='Your Experience', max_length=200),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='Skill',
            field=models.CharField(default='Your skills', max_length=200),
        ),
        migrations.AddField(
            model_name='registrationform',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_image'),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
