# Generated by Django 2.1.1 on 2018-09-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appa', '0004_auto_20180920_2348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='user',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
