# Generated by Django 2.1.1 on 2018-09-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appa', '0005_auto_20180921_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registrationform',
            name='image',
            field=models.ImageField(blank=True, upload_to='appa/templates/html/profile_image'),
        ),
    ]
